name: Semgrep OSS

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep OSS Scan
        uses: semgrep/semgrep:latest
        with:
          config: p/default
